### ISSUE TITLE
TILE_UPDATE isn't working for farming

### ISSUE THREAD

**Issue by amos1814** [borrascador/rain#131]

**Comment by borrascador** [comment]
Hey I just noticed that players are only able to harvest crops that are in their starting inventory already. Otherwise the player sees the crop, tries to harvest it, and gets a bad payload (only item id and quantity, but no name or tags, which should be sent if the player doesn't have the item already).

This is exactly the situation where you would want the client to catch this error and send that info to the server, I think I'd call this error 303 from our new list "EVENT_RESULT bad payload"
