### ISSUE TITLE
Remove NPCs from party

### ISSUE THREAD

**Issue by amos1814** [borrascador/rain#318]
Get rid of "NPC" field in party member list

Only player-controlled party members will be tracked. When a party member logs out, the following update will be sent:

```
{
   "payload": {"party": [{
      "status" : "offline"
      "id": int
   }]},
   "type": "UPDATE"
}
```

Similarly when a party member logs in
```
{
   "payload": {"party": [{
      "status" : "online"
      "yCoord": int,
      "yPos": int,
      "xCoord": int,
      "xPos": int,
      "id": int
   }]},
   "type": "UPDATE"
}
```

**Comment by amos1814** [comment]
Also add a message in chat for logging in and out

**Comment by borrascador** [comment]
Thinking about it again, it seems that this issue is a good chance to talk about session end behavior more broadly. I suggest we build from this protocol for the following cases:

When any party member, player, or npc has health <= 0, then the server can send a "dead" message and also add the inventory object of that player to the party member for looting, and block any incoming moves for that entity. If it is a party member, they are allowed to observe (receive real-time data) and chat and they are not removed from the party, they simply have a "dead" status visible. If there is a resurrection ability, it can happen here because the player is still taking up their slot and observing. However, if the player logs out or leaves the party or is kicked out of the party then they are unassociated and the party slot opens up for a new player to join. By the way, we could have an advanced feature later to ban kicked out players so they can't rejoin.

Anyway what do you think? Wondering if a "dead"/"alive" flag is a good starting point, and what you think of finer details.

**Comment by borrascador** [comment]
One more thing, `status` is probably the wrong name for this variable. Can we do `"online": bool` instead?

**Comment by borrascador** [comment]
96b0324 includes changes that will show a player as offline if `online: false` and a player as dead if `health <= 0`

After server has implemented `online: bool`, I will adjust the logic to check for online true instead of false.

**Comment by amos1814** [comment]
Change party generation

Old: Every party member is generated when party is created

New: Party member is generated upon joining a party

Max party size is 3 for now

**Comment by borrascador** [comment]
While you're at it, I found a bug where the current party member shows up as `online: false, self: true` while the leftover npc characters have `online: true`.

**Comment by amos1814** [comment]
The avatar doesn't disappear when a player logs out. Should we make it so it does?

~~~~
{
   "payload": {
      "messages": [{"text": "b has logged out."}],
      "party": [{
         "online": false,
         "id": 1
      }]
   },
   "type": "UPDATE"
}
~~~~

**Comment by borrascador** [comment]
I made it so the avatar grays out to communicate offline status. The avatar is still there unless that party member is removed from the group.

**Comment by borrascador** [comment]
By the way I found a bug with the new implementation: if I am in a party and someone else joins or logs in, then the other player's data has `self: true`. The result is that multiple players have the red background which is supposed to indicate `self: true`.

**Comment by borrascador** [comment]
Overall this is a lot better though thanks :+1:

**Comment by amos1814** [comment]
I'll fix that right now forgot about the self field
